name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./tests/Dockerfile
        tags: test:latest
        load: true  # This is important for running the image locally in the next step

    - name: Run tests
      run: |
        docker run -v ./results:/app/results --rm test:latest

    - name: Upload test coverage result
      uses: codecov/codecov-action@v3
      with:
        directory: ./results
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: false
