name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Build
      run: dotnet build

    - name: Run unit tests
      run: |
        dotnet test tests/Socks5.Net.UnitTests --no-restore --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results
        dotnet test tests/Socks5.Net.Extensions.UnitTests --no-restore --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results
    
    - name: Run integration tests
      run: |
        dotnet test tests/Socks5.Net.IntegrationTests --no-restore --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results

    - name: Upload test coverage result
      uses: codecov/codecov-action@v3
      with:
        directory: ./results
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: false
