name: Release

on: 
  push:
    tags:
    - 'v*'
jobs:
  binary:
    name: release executable
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Get tool version on linux
      run: |
        version=` grep '<Version>' < tools/Client/Client.csproj | sed 's/.*<Version>\(.*\)<\/Version>/\1/'`
        echo "VERSION=$(echo -n ${version})" >> $GITHUB_ENV
      if: matrix.os == 'ubuntu-latest'

    - name: Get tool version on windows
      run: |
        $xml = [Xml] (Get-Content tools/Client/Client.csproj)
        $version = $xml.Project.PropertyGroup.Version
        $GITHUB_ENV=$GITHUB_ENV + "VERSION=${version}"
      if: matrix.os == 'windows-latest'

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build -c release

    - name: Run unit tests
      run: |
        dotnet test tests/Socks5.Net.UnitTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results
        dotnet test tests/Socks5.Net.Extensions.UnitTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results
    
    - name: Run integration tests
      run: |
        dotnet test tests/Socks5.Net.IntegrationTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results

    - name: Publish self-contained binaries on linux
      run: |
        dotnet publish -c release tools/Client/Client.csproj -r linux-x64 --self-contained true -o ./bin -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish -c release tools/SocksServer/SocksServer.csproj -r linux-x64 --self-contained true -o ./bin -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        ./bin/Client -h
        ./bin/SocksServer -h
        mv ./bin/Client ./bin/sclient_linux-x64_${VERSION}
        mv ./bin/SocksServer ./bin/sserver_linux-x64_${VERSION}
      if: matrix.os == 'ubuntu-latest'

    - name: Publish self-contained binaries on windows
      run: |
        dotnet publish -c release tools/Client/Client.csproj -r win-x64 --self-contained true -o ./bin -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish -c release tools/SocksServer/SocksServer.csproj -r win-x64 --self-contained true -o ./bin -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        ./bin/Client.exe -h
        ./bin/SocksServer.exe -h
        mv ./bin/Client.exe ./bin/sclient_win-x64_${VERSION}.exe
        mv ./bin/SocksServer.exe ./bin/sserver_win-x64_${VERSION}.exe
      if: matrix.os == 'windows-latest'

    - name: Upload release assets for Linux
      uses: svenstaro/upload-release-action@v2
      if: matrix.os == 'ubuntu-latest'
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/*linux-x64*
          tag: ${{ github.ref }}
          file_glob: true
          prerelease: true
          overwrite: true

    - name: Upload release assets for Windows
      if: matrix.os == 'windows-latest'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./bin/*win-x64*
        tag: ${{ github.ref }}
        file_glob: true
        prerelease: true
        overwrite: true

  nuget:
    name: publish nuget to nuget.org
    needs: binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build -c release

    - name: Run unit tests
      run: |
        dotnet test tests/Socks5.Net.UnitTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results
        dotnet test tests/Socks5.Net.Extensions.UnitTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results
    
    - name: Run integration tests
      run: |
        dotnet test tests/Socks5.Net.IntegrationTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results

    - name: Push nuget package
      run: |
        dotnet nuget add source --username Hugozys --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Hugozys/index.json"        
        dotnet nuget push "package/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s github --skip-duplicate
        dotnet nuget push "package/*.nupkg" -k ${API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY }}
