name: Release

on: 
  push:
    tags:
    - 'v*'
jobs:
  build_release:
    name: release executable
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            release_suffix: linux
          - os: windows-latest
            release_suffix: win
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build -c release

    - name: Run unit tests
      run: |
        dotnet test tests/Socks5.Net.UnitTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results
        dotnet test tests/Socks5.Net.Extensions.UnitTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results
    
    - name: Run integration tests
      run: |
        dotnet test tests/Socks5.Net.IntegrationTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results

    - name: Publish self-contained binaries on linux
      run: |
        dotnet publish -c release tools/Client/Client.csproj -r linux-x64 --self-contained true -o ./bin -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish -c release tools/SocksServer/SocksServer.csproj -r linux-x64 --self-contained true -o ./bin -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        ./bin/Client -h
        ./bin/SocksServer -h
        mv ./bin/Client ./bin/sclient_linux_x64_${{ github.ref_name }}
        mv ./bin/SocksServer ./bin/sserver_linux_x64_${{ github.ref_name }}
      if: matrix.os == 'ubuntu-latest'

    - name: Publish self-contained binaries on windows
      run: |
        dotnet publish -c release tools/Client/Client.csproj -r win-x64 --self-contained true -o ./bin -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish -c release tools/SocksServer/SocksServer.csproj -r win-x64 --self-contained true -o ./bin -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        ./bin/Client.exe -h
        ./bin/SocksServer.exe -h
        mv ./bin/Client.exe ./bin/sclient_win_x64_${{ github.ref_name }}.exe
        mv ./bin/SocksServer.exe ./bin/sserver_win_x64_${{ github.ref_name }}.exe
      if: matrix.os == 'windows-latest'

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        draft: true
        prerelease: true
        files: |
          ./bin/sclient_${{ matrix.release_suffix }}_x64_${{ github.ref_name }}*
          ./bin/sserver_${{ matrix.release_suffix }}_x64_${{ github.ref_name }}*

  nuget:
    name: publish nuget to nuget.org
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build -c release

    - name: Run unit tests
      run: |
        dotnet test tests/Socks5.Net.UnitTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results
        dotnet test tests/Socks5.Net.Extensions.UnitTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results
    
    - name: Run integration tests
      run: |
        dotnet test tests/Socks5.Net.IntegrationTests --no-restore -c release --collect:"XPlat Code Coverage" --settings ./tests/coverlet.runsettings --results-directory ./results

    - name: Push nuget package
      run: |
        dotnet nuget add source --username Hugozys --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Hugozys/index.json"        
        dotnet nuget push "package/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s github --skip-duplicate
        dotnet nuget push "package/*.nupkg" -k ${API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY }}
